### ISSUE TITLE
Ideação de possíveis projetos

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#1]
## Nome da Issue
Ideação de possíveis projetos

## Descrição da Issue
Na reunião do dia 6/2/2021 foram escolhidos três temas a serem apresentados para o professor Hilmer na aula de terça. O time de MDS deverá se dividir em 3 duplas para poder realizar uma ideação mais detalhada de cada tema.

As duplas são:
- Arthur e Sabanai, com o tema A: App para adoção de animais perdidos.
- - Brian e Luiz, com o tema B: App que troque ações sociais por pontos
- Buendia e Nicolas, com o tema C: App de rotina saudável de estudos e compilado de materiais de saúde mental

Cada dupla deverá listar ideias de como esses temas podem ser trabalhados em um contexto de software. É recomendada a utilização de protótipo de baixa fidelidade ou mapa mental, entretanto, não é obrigatório ou restrito nenhuma das opções. A dupla pode decidir como proceder. 

![Temas](https://user-images.githubusercontent.com/37380789/107122577-371d5c00-6877-11eb-84bb-3b263e12370c.jpg)

### Tasks:
- Listar ideias gerais de como a ideia pode ser abordada em contexto de software (não precisa ser extremamente detalhado)

### Critérios de aceitação:
- [x] Dupla Buendia e Nicolas
- [x] Dupla Brian e Luiz
- [x] Dupla Arthur e Sabanai

**Comment by luiz-herique** [comment]
**Identificação**

**Nome:** Luiz Henrique Fernandes Zamprogno - 19/0033681
**Nome:** Brian Pina de Sa - 19/0010967

**Features**

Ideia: Aplicativo que visa proporcionar através de elementos de gamificação a troca de serviços(ajudas) entre a comunidade.

Protótipo de Baixa Fidelidade: 
www.figma.com/file/KiTicUGvgeOQkgw6BhpHfv/MDS-Wireframe?node-id=243%3A1

**Funcionalidades**

Cadastro:
- Cadastro de usuário;
- Confirmação por e-mail.
Login:
- Realizar Login;
- Recuperar senha por email;
Pedidos:
- Visualizar pedidos;
- Pesquisar pedidos;
- Comentar em pedidos;
- Compartilhar pedidos;
- Aceitar pedidos;
- Ver solicitações de realização de pedido;
- Aceitar solicitações de realização de pedido;
- Criar pedido com base em meus pontos(Oferta arbitrária);
- Criar pedidos com base em minha localização;
- Editar pedido;
- Excluir pedido;
- Validar a realização de pedido de outro usuário;
- Dar nota para a realização do serviço;
- Adquirir pontos na realização do pedido;	
- Denúncia de não realização;
- Denúncia de não validação de conclusão;
Usuário:
- Chat de usuários;
- Editar perfil;
- Editar foto de perfil.

**Link para o documento no Drive do projeto:**
docs.google.com/document/d/1kLX1g8NqQrzXsem_0GqjuIeqhz6Tncn7p0UjuLxEHpc/edit

**Comment by nszchagas** [comment]
**Identificação**

Nome: Nicolas Chagas Souza - 20/0042327
Nome: Victor Buendia Cruz de Alvim - 19/0020601

**Features**

Ideia: aplicativo que busca promover uma rotina saudável de estudos, a partir da facilitação na conciliação entre vida pessoal e profissional, com compilado de conteúdos sobre saúde mental. 

[Protótipo de baixa fidelidade](https://miro.com/app/board/o9J_lVC-W9A=/?moveToWidget=3074457354245565222&cot=14 )

**Funcionalidades**

A definição das funcionalidades foi feita por meio de brainstorming utilizando post-its na plataforma Miro. Em seguida, as funcionalidades foram classificadas quanto a prioridade, utilizando o método MoSCoW, em: Must, Should, Could e Would, sendo Must as essenciais para o funcionamento e proposta do aplicativo e Would as com menor prioridade.
Em ordem decrescente de prioridade, as funcionalidades são: 

Must have: 

- Opção para inserir as disciplinas do semestre - Nome, número de créditos (ou carga horária), dificuldade e cronograma de aulas;
- Cronograma semanal com as informações inseridas;
- Um cronômetro que conta o tempo que você gastou estudando uma certa matéria (para melhorar a eficiência e se planejar melhor);
- Opção para inserir atividades de lazer e frequência desejada;
- Controle de notas e faltas;
- Gráfico para ver quanto tempo você gasta estudando, com a família, lazer, etc;
- Contagem regressiva para as provas;

Should have: 

- Opção de lembrete diário de atividades (ou de rotina);
- Lembretes de revisão dos estudos de acordo com a Curva do Esquecimento;
- Um pomodoro ajustável integrado para melhorar o foco e elevar a produtividade;
- Compilado de dicas de saúde mental;
- Priorização de estudos por dificuldade das matérias;
- Algum gráfico para ver a evolução na consistência de estudos;

Could have: 

- Sincronizar os compromissos de app de agenda (ex. google agenda);
- Calculadora de tempo sugerido de estudo baseado na dificuldade das disciplinas;
- Dicas para ser produtivo no estudo e gastar menos tempo estudando;
- Possibilidade de estipular metas e recompensa por metas cumpridas (medalhas);
- Streaks para dias seguindo a rotina de estudo;
- O pomodoro linkado com o tempo que eu gasto para estudar as matérias (acumular dados sobre o meu tempo de estudo);

Would have: 

- Um gif para exercitar a respiração e acalmar o estresse;
- Aba de textos para distrair (como do pocket);
- Ao se aproximar das provas, o app solta mensagens sobre cuidar da ansiedade, nervosismo, etc;
- Calcular previsões de notas que você precisa para passar;
- Possibilidade de criar grupos de estudo/material compartilhado;
- Mensagens motivacionais sobre o progresso do usuário;

**Comment by Sabanai104** [comment]
**Identificação** 

Nome: Arthur Alves de Matos - 19/0010495
Nome: Gabriel Sabanai Trindade - 19/0028122

**Features**

Ideia: Plataforma que visa conectar interessados em adotar animais com resgatantes, tem como objetivo ser um facilitador na procura de um dono para animais resgatados e perdidos. Além disso, ia conter dicas de procedimentos a serem tomados quando se encontra um animal perdido ou machucado e contato de ongs que dão apoio à prática. 

obs: Achamos desnecessário a criação de um protótipo de baixa fidelidade, por existir já diversos aplicativos de compra e venda que passam mais ou menos a ideia da plataforma.

**Funcionalidades** 

Cadastro:
Cadastro de usuário;
Nome completo
E-mail
Senha
Localização
Num de telefone
Perguntas para saber se possui um espaço ideal para adotar o animal (apenas pra usuários que vão adotar)
Confirmação por e-mail.

Login:
Realizar Login;
Recuperar senha por email;

Usuário:
Editar Perfil;
Chat de Usuários;

Característica:

Incluir foto;
Descrição do usuário;
Tipo de usuário (Pessoa física/Organização);

Anuncio de animais:
Realizar anúncio;
Editar Anúncio;
Listagem de Anúncios
Busca por anúncios;
Busca de anúncios por Organização;
Excluir anuncio;
Solicitar contato;
Aceitar contato;
Contatar Anunciante;
Incluir imagem do animal ao anúncio;
Filtrar animais do anúncio;
Chat para entrar em contato;

Pagina de suporte e contato
Guia com dicas de procedimentos
Guia com número de contato de Ongs
		
    		


Características da feature Anúncio:

Indicar localização do resgate do animal;
Indicação de condição e temperamento do animal;
Indicação de possíveis cuidados médicos já realizados;
Indicar descrição da personalidade do animal;
Indicar características sobre espécie;
Mensurar um gasto mensal necessário com o animal (gasto de comida, remédio, etc.)
