### ISSUE TITLE
Richpicture do produto

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#17]
## Nome da Issue
Richpicture do produto

## Descrição da Issue
Criar um richpicture que exemplifique o fluxo de interação do usuário com a possível aplicação.

### Tasks:
- [x] Criar o RichPicture
- [x] Linkar usuários, tarefas

### Critérios de aceitação
- [ ] RichPicture feito em uma plataforma de edição
- [ ] Usuários e fluxos bem definidos
- [ ] Não pode ser centralizado

**Comment by Victor-Buendia** [comment]
Fiz meu Rich Picture no [nosso Miro](https://miro.com/app/board/o9J_lVC-W9A=/?moveToWidget=3074457354614198167&cot=14). Se tiverem alguma sugestão de melhora, só me mandar.
![image](https://user-images.githubusercontent.com/54643355/108205745-3c469a80-7104-11eb-8613-c71269c279d0.png)

**Comment by MatheusBlanco** [comment]
> Fiz meu Rich Picture no [nosso Miro](https://miro.com/app/board/o9J_lVC-W9A=/?moveToWidget=3074457354614198167&cot=14). Se tiverem alguma sugestão de melhora, só me mandar.
> ![image](https://user-images.githubusercontent.com/54643355/108205745-3c469a80-7104-11eb-8613-c71269c279d0.png)

Massa, gostei bastante. Só fiquei em dúvida naquela conexão de problemas entre o cidadão comum e problemas comunitários, na setinha do "não". O que significaria?

**Comment by devsalula** [comment]
> Fiz meu Rich Picture no [nosso Miro](https://miro.com/app/board/o9J_lVC-W9A=/?moveToWidget=3074457354614198167&cot=14). Se tiverem alguma sugestão de melhora, só me mandar.
> ![image](https://user-images.githubusercontent.com/54643355/108205745-3c469a80-7104-11eb-8613-c71269c279d0.png)

Curti também, dá para ver os fluxos e não tá parecendo um mapa mental.
Mas a mesma coisa do @MatheusBlanco , essa seta "Não" ela tá meio perdida dentro da representação. Acho que pode tirar.

**Comment by Victor-Buendia** [comment]
@devsalula e @MatheusBlanco , essa do "não" era "o cidadão comum não tem problemas comunitários", mas já tirei. Realmente ficou isolado. Obrigado!

**Comment by devsalula** [comment]
> @devsalula e @MatheusBlanco , essa do "não" era "o cidadão comum não tem problemas comunitários", mas já tirei. Realmente ficou isolado. Obrigado!

Perfeito! Parabéns pelo Trabalho!
Pode colocar aqui a versão final?

**Comment by luiz-herique** [comment]
Rich Picture - Luiz Henrique

![+](https://user-images.githubusercontent.com/62183792/108370402-60c17600-71db-11eb-8c80-41af0e992f3e.png)

**Comment by MatheusBlanco** [comment]
> Rich Picture - Luiz Henrique
> 
> ![+](https://user-images.githubusercontent.com/62183792/108370402-60c17600-71db-11eb-8c80-41af0e992f3e.png)

Massa Luiz, desculpe pela demora. Só não entendi a parte da pessoa ganhar pontos por baixar o sistema. Seria tipo um bônus? Acho que seria legal representar a parte do comércio dos pontos também, e sobre o problema identificado ser cadastrado na plataforma.

**Comment by Arthur-Matos** [comment]
![EPS-MDS - Rich Picture - Arthur (1)](https://user-images.githubusercontent.com/64804162/108405007-54e7ab00-71ff-11eb-864c-f71cd4139065.jpg)

**Comment by Victor-Buendia** [comment]
@devsalula A versão final, como você havia pedido. Desculpe pelo delay.
![image](https://user-images.githubusercontent.com/54643355/108408764-333cf280-7204-11eb-8bb3-6454b8abd126.png)

**Comment by Phe0** [comment]
![photo5005765327174347118](https://user-images.githubusercontent.com/31973465/108409662-44d2ca00-7205-11eb-83d7-64f6d318b168.jpg)

**Comment by MatheusBlanco** [comment]
![image](https://user-images.githubusercontent.com/37380789/108519683-a4ce7c80-72a8-11eb-9c29-340ff794cfa6.png)

**Comment by devsalula** [comment]
![rp](https://user-images.githubusercontent.com/35435199/108559721-75d0fe80-72da-11eb-9d8b-465704ebb13b.png)

**Comment by nszchagas** [comment]
![EPS-MDS - Rich Picture - Nicolas](https://user-images.githubusercontent.com/68018675/108567265-adde3e80-72e6-11eb-81d5-b99b18a443f9.jpg)

**Comment by Sabanai104** [comment]
Terminei meu Rich Picture, desculpaa a demora!

![EPS-MDS - Rich Picture - Sabanai](https://user-images.githubusercontent.com/51263792/108576565-e1c45e80-72fc-11eb-949b-b8a4cfec1ca4.jpg)

**Comment by DLBrianPina** [comment]
Malz pela demora. Está melhor lá no Miro os detalhes.
![EPS-MDS - Rich Picture Brian](https://user-images.githubusercontent.com/51856934/108579808-7338ce00-7307-11eb-98fe-63e98a3fe978.jpg)
