### ISSUE TITLE
Forms da problemática

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#18]
## Nome da Issue
Formulário de pesquisa da problemática

## Descrição da Issue
Realizar um formulário de pesquisa de opinião para comunidades públicas sobre problemas enfrentados por elas e como foi a resolução dos mesmos (se teve ação do estado, agentes terceiros e afins)

### Tasks:
- [x] Criar o forms
- [x] Coletar respostas
- [ ] Analisar as mesmas para aplicar no lean inception

### Critérios de aceitação
- [x] Entender qual foi a ação do estado sobre os problemas
- [x] Entender como isso afetou a vida das pessoas na comunidade.
