### ISSUE TITLE
Trocar versão da Wiki

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#20]
## Nome da Issue
Trocar versão da Wiki

## Descrição da Issue
A wiki está 3 versões atrasada e deve ser atualizada para a versão 6. Para fazer isso, o curso ideal seria o de subir um novo MKDOCS e transferir os dados para lá. Outro curso, menos ideal seria atualizar a que a gente já tem e arrumar os bugs.

### Tasks:
- [ ] Atualizar a versão da Wiki
- [ ] Arrumar bugs/transferir configurações para a nova versão

### Critérios de aceitação
- [ ] Wiki subindo normalmente
- [ ] Documentos preservados
