### ISSUE TITLE
Elaborar treinamento de Figma

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#21]
## Nome da Issue
Elaborar treinamento de Figma

## Descrição da Issue
Criar um treinamento de figma para que o time de MDS possa se capacitar em criar protótipos de alta fidelidade, com conceitos de frames, componentes, conexões, páginas e elementos afins.

### Tasks:
- [x] Elaborar treinamento
- [ ] Aplicar treinamento
- [x] Criar atividade prática

### Critérios de aceitação
- [ ] Ter os conceitos necessários para a criação de um protótipo (frame, página, scroll, animação e conexões, componentes)
- [ ] Slides e parte prática
