### ISSUE TITLE
Documentar o gerenciamento de riscos do projeto

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#22]
## Nome da Issue
Documentar o gerenciamento de riscos do projeto.

## Descrição da Issue
Deve-se fazer um gerenciamento de riscos do projeto de acordo com os preceitos do PMBOK, focando principalmente em questões como ação do estado, burocracias necessárias e que podem impedir nossa futura solução de existir. [Exemplo](https://escritoriodeprojetos.com.br/artigos-de-gerenciamento-dos-riscos),
[Kalkuli](https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/tap)

### Tasks:
- [x] Criar documento de gerenciamento de riscos
- [ ] Utilizar da problemática e das reflexões do hilmer para construir uma noção dos riscos existentes ao projeto (burocracia, falta de engajamento do produto..., análise quantitativa e qualitativa separando os riscos em graus de periculosidade, riscos de equipe, custos e metodologia)

### Critérios de aceitação
- [ ] Lista de riscos com graus de periculosidade

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.
