### ISSUE TITLE
Quest #3 - Problema e Concorrentes

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#23]
## Nome da Issue
Quest #3 - Problema e Concorrentes

## Descrição da Issue
Utilizar da metologia Projetão para continuar a exploração da problemática. Dessa vez, utilizar das pesquisas e análises coletadas em Sprint Planning para responder as perguntas.

### Tasks:
- [x] Compilar e abstrair os resultados da sprint planning
- [x] Responder as perguntas da Quest #3

### Critérios de aceitação
- [x] Respostas da quest #3 ajudam a definir mais a problemática
- [x] Ser capaz de utilizar as respostas para poder construir os primeiros passos do Lean Inception

**Comment by MatheusBlanco** [comment]
@luiz-herique e @Sabanai104 ficaram com a missão de avaliar os resultados do forms e ajustar as respostas de acordo com os mesmos. É o que está faltando para completar a issue.
