### ISSUE TITLE
Lean Inception - Início

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#24]
## Nome da Issue
Lean Inception - Início

## Descrição da Issue
A partir das respostas obtidas na sprint planning e, futuramente, do formulário da problemática e da quest número 3 da metodologia projetão, realizar 3 etapas do processo de Lean Inception

### Tasks:
- [x] Formular Visão do Produto
- [x] Formular Objetivos do produto
- [x] Formular Personas

### Critérios de aceitação
- [x] Escopo da problemática e do produto bem definidos
- [x] De fácil entendimento

**Comment by MatheusBlanco** [comment]
https://app.mural.co/invitation/mural/fgaepsmds202027717/1613056199650?sender=ud8413517a97742009ec54625&key=a5e2bf67-d258-413c-9fe6-58f12d85594f

**Comment by MatheusBlanco** [comment]
Vou usar a sprint review para completar os objetivos, com uma dinâmica de grupo.

**Comment by MatheusBlanco** [comment]
@devsalula @Phe0 @guilhesme23 @Victor-Buendia @luiz-herique @DLBrianPina @Arthur-Matos @nszchagas @Sabanai104 , se puderem revisar.
