### ISSUE TITLE
Documentação Sprint 0

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#25]
## Nome da Issue
Documentação Sprint 0

## Descrição da Issue
Adicionar à wiki a documentação de review e retrospectiva, bem como os gráficos de burndow, velocity, cycle, cumulative flow, resumo das tarefas realizadas, riscos, humor e conhecimento dos membros, bem como avaliação do [Scrum Master](https://github.com/Phe0) sobre o avanço do time no projeto e problemas enfrentados. 

### Tasks:
- [x] Avaliação do Scrum Master
- [x] Reports (burndown, velocity, cycle, cumulative flow)
- [x] Tarefas realizadas e riscos
- [x] Humor e conhecimento dos membros

### Critérios de aceitação
- [x] Documentação na wiki
- [x] Gráficos visuais e de acordo com esperados da disciplina
- [x] Anotações concisas e de fácil entendimento
