### ISSUE TITLE
Documentação Planning Sprint 1

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#27]
## Nome da Issue
Documentação Planning Sprint 1

## Descrição da Issue
Adicionar à wiki a documentação de planning da sprint em questão contendo as duplas de pareamento definidas, as issues/histórias de usuário escolhidas para serem trabalhadas, contendo pontuação e encarregados da mesma. 

### Tasks:
- [x] Duplas de pareamento
- [x] Issues/histórias de usuário

### Critérios de aceitação
- [x] Documentação na wiki
- [x] Justificativa para escolha dos pareamentos
- [x] Tabela de issues com responsáveis e pontuação estimada
