### ISSUE TITLE
Termo de abertura de projeto

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#33]
## Nome da Issue
Elaborar Termo de abertura de projeto

## Descrição da Issue
Criar o documento de abertura de projeto, com seções como justificativa, objetivo, produto, requisitos de alto nível, restrições, riscos, cronograma, stakeholders e custos estimados

### Tasks:
- [x] Introdução
- [x] Justificativa
- [x] Objetivo
- [x] Produto
- [x] Requistos de alto nível
- [x] Restrições
- [x] Riscos
- [x] Cronograma
- [x] Stakeholders
- [x] Custos

### Critérios de aceitação
- [x] Documento com todas as seções escritas
- [x] Referências
- [x] De acordo com nosso tema

**Comment by MatheusBlanco** [comment]
Referência: https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/tap

**Comment by Phe0** [comment]
documentação está sendo realizada no fork e branch 
https://github.com/Victor-Buendia/EPS-2020-2-G2/tree/doc_tap

**Comment by Victor-Buendia** [comment]
Só estou realizando agora na branch _doc_tap_ aqui neste repositório original.
