### ISSUE TITLE
Documento de visão

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#34]
## Nome da Issue
Elaborar documento de visão

## Descrição da Issue
Elaborar o documento de visão do projeto que descreve questões mais técnicas e de produto do projeto. Deve conter as seções descritas abaixo.

### Tasks:
- [x] Finalidade
- [x] Escopo
- [x] Não escopo
- [x] Definições, acrônimos e abreviações
- [x] Visão geral
- [x] Oportunidade de negócios
- [x] Descrição do problema
- [x] Sentença de posição do produto
- [x] Descrição dos envolvidos e usuários
- [x] Perspectiva do produto
- [x] Resumo dos recursos
- [x] Recursos do produto

### Critérios de aceitação
- [ ] Com todos os tópicos bem escritos
- [ ] De acordo com nosso tema
- [ ] Com referências

**Comment by MatheusBlanco** [comment]
Referência: https://fga-eps-mds.github.io/2018.2-Kalkuli/docs/docVisao
