### ISSUE TITLE
Lean Inception

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#35]
## Nome da Issue
Fechar as etapas finais do Lean Inception

## Descrição da Issue
Terminar o lean inception, de acordo com o que foi discutido em reunião de planning.

### Tasks:
- [x] Jornada de usuário
- [x] Funcionalidades
- [x] Revisão técnica
- [x] Sequenciador
- [x] Canvas MVP

### Critérios de aceitação
- [x] Todas as etapas concluídas
- [x] De acordo com nossa temática
