### ISSUE TITLE
Requisitos de benchmarking

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#36]
## Nome da Issue
Requisitos de benchmarking

## Descrição da Issue
Retirar os requisitos de concorrentes a partir de pesquisas de benchmarking. Criar um documento listando os requisitos retirados dos concorrentes e que podem ser aproveitados no projeto.

### Tasks:
- [x] Pesquisar concorrentes
- [x] Identificar os requisitos
- [x] Anotar aqueles que podem ser aproveitados em nosso projeto

### Critérios de aceitação
- [x] Documento de requisitos
- [x] Requisitos elicitados
