### ISSUE TITLE
Requisitos de Questionário

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#37]
## Nome da Issue
Requisitos do questionário

## Descrição da Issue
Retirar os requisitos do questionário a partir de análises do mesmo. Criar um documento listando os requisitos retirados das respostas e que podem ser aproveitados no projeto.

### Tasks:
- [x] Analisar respostas
- [x] Identificar os requisitos
- [x] Anotar aqueles que podem ser aproveitados em nosso projeto

### Critérios de aceitação
- [x] Documento de requisitos
- [x] Requisitos elicitados

**Comment by nszchagas** [comment]
Compilei os gráficos e respostas das perguntas abertas do questionário nesse [arquivo](https://docs.google.com/document/d/1DN6lC2QkT5t8c-mFLUMVMYuX1NseUET7Mu764dOVLT8/edit?usp=sharing) do drive. 

A partir das respostas montei uma lista de requisitos e montei o [documento dos requisitos](https://drive.google.com/file/d/1q2sLDQ50FUWHA4U8iF-1rERu-vhCv_O_/view?usp=sharing). Na lista classifiquei em prioridades. 

Se alguém tiver alguma sugestão ou mais ideias é só me avisar que arrumo.

**Comment by nszchagas** [comment]
# Requisitos elicitados referentes ao questionário 

## Introdução

O questionário de viabilidade foi aplicado pela equipe e com base nas perguntas e respostas recebidas foram elencadas os requisitos abaixo. Os requisitos foram priorizados seguindo o método MosCoW.

## Requisitos elicitados

| Código | Descrição                                                                                                                                                                          | Prioridade | Pergunta        |
|--------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|-----------------|
| Q01    | A aplicação deverá permitir que o usuário faça denúncias de problemas para o Estado.                                                                                               | Must       | Perguntas 2 e 3 |
| Q02    | A aplicação poderá permitir que o usuário identifique o órgão público responsável pela solução do problema (Anvisa, Detran, Ministério Público, CEB, CAESB).                       | Could      | Pergunta 2      |
| Q03    | A aplicação poderá apresentar uma maneira de outros usuários validarem (upvote) ou não as denúncias feitas pelos usuários.                                                         | Must| Pergunta 8.1    |
| Q04    | A aplicação poderá conter uma guia com informações sobre legislação.                                                                                                               | Would      | Pergunta 3.1    |
| Q05    | A aplicação poderá conter um feed com as denúncias mais próximas.                                                                                                                  | Must| Pergunta 8.1    |
| Q06    | A aplicação poderá conter a opção de comentar as denúncias mais próximas.                                                                                                          | Would      | Pergunta 8.1    |
| Q07    | A aplicação poderá restringir as denúncias mostradas por um raio de acordo com a localização do usuário.                                                                           | Must| Pergunta 8.1    |
| Q08    | A aplicação deverá ter um formulário simples para denúncia de problemas, com dados essenciais para envio aos órgãos públicos.                                                      | Must       | Pergunta 8.1    |
| Q09    | A aplicação poderá agrupar as denúncias de acordo com categorias pré-estabelecidas (Ex. Problemas elétricos, Saneamento Básico, Vias Públicas).                                    | Could      | Pergunta 8.1    |
| Q10    | A aplicação poderá conter elementos lúdicos, como emblemas e metas.                                                                                                                | Could      | Pergunta 8.1    |
| Q11    | A aplicação deverá fazer a comunicação com o Estado, enviando as denúncias pelos meios definidos por cada órgão público (e-mail ou telefonemas).                                   | Must       | Pergunta 8.1    |
| Q12    | A aplicação deverá mostrar o status das denúncias (ex: encaminhadas ao estado, respondidas pelo estado e resolvidas pelo estado/moradores) com a data de hora de cada atualização. | Must       | Pergunta 8.1    |
| Q13    | A aplicação poderá conter recursos de acessibilidade para usuários cegos e surdos.   | Could | Pergunta 8.1

**Comment by devsalula** [comment]
@nszchagas tem como você subir o documento de requisitos sem a extensão .md? 
Eu gostaria de poder comentar no documento, e ele só está abrindo para mim apenas a leitura e não a edição.

**Comment by Phe0** [comment]
@nszchagas se puder fazer uma página na wiki com essas coisas e abrir um PR.
Se não souber como fazer pode chamar.
