### ISSUE TITLE
Documentar resultados da reunião do dia 06 de Fevereiro de 2021

### ISSUE THREAD

**Issue by devsalula** [fga-eps-mds/EPS-2020-2-G2#4]
## Descrição da Issue
Documentar na Wiki os assuntos discutidos e os resultados obtidos da reunião do dia 06 de Fevereiro de 2021.

### Tasks:
- [x] Definir um formato de documentação
- [x] Documentar na Wiki

### Critérios de aceitação
- [x] Abordar a definição das ferramentas de comunicação
- [x] Abordar horário das reuniões e rituais das dailies
- [x] Abordar o quadro de conhecimento
- [x] Abordar a definição do tema

## Assignees
@Phe0
