### ISSUE TITLE
Documentação Sprint 1

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#40]
## Nome da Issue
Documentação Sprint 1

## Descrição da Issue
Adicionar à wiki a documentação de review e retrospectiva, bem como os gráficos de burndow, velocity, cycle, cumulative flow, resumo das tarefas realizadas, riscos, humor e conhecimento dos membros, bem como avaliação do [Scrum Master](https://github.com/Phe0) sobre o avanço do time no projeto e problemas enfrentados. 

### Tasks:
- [ ] Avaliação do Scrum Master
- [ ] Reports (burndown, velocity, cycle, cumulative flow)
- [ ] Tarefas realizadas e riscos
- [ ] Humor e conhecimento dos membros

### Critérios de aceitação
- [ ] Documentação na wiki
- [ ] Gráficos visuais e de acordo com esperados da disciplina
- [ ] Anotações concisas e de fácil entendimento
