### ISSUE TITLE
Documentação Planning Sprint 3

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-eps-mds/EPS-2020-2-G2#47]
## Nome da Issue
Documentação Planning Sprint 3

## Descrição da Issue
Adicionar à wiki a documentação de planning da sprint em questão contendo as duplas de pareamento definidas, as issues/histórias de usuário escolhidas para serem trabalhadas, contendo pontuação e encarregados da mesma. 

### Tasks:
- [ ] Duplas de pareamento
- [ ] Issues/histórias de usuário

### Critérios de aceitação
- [ ] Documentação na wiki
- [ ] Justificativa para escolha dos pareamentos
- [ ] Tabela de issues com responsáveis e pontuação estimada
