### ISSUE TITLE
Planejar Treinamento de Git para MDS

### ISSUE THREAD

**Issue by devsalula** [fga-eps-mds/EPS-2020-2-G2#8]
## Descrição da Issue
Criar e executar um treinamento básico de Git para os MDS's baseado nas respostas que deram na enquete de conhecimento.

### Tasks:
- [x] Preparar slides do treinamento
- [x] Preparar repositório do treinamento
- [x] Agendar o horário do treinamento

### Critérios de aceitação
- [ ] Todos os MDS's precisam saber o mínimo para poder sobreviver na disciplina.

## Assignees
@devsalula

**Comment by devsalula** [comment]
Treinamento preparado:
https://docs.google.com/presentation/d/1y9VYDxEpk0CyhwSKBllCYXwVaehs_sVkisLUzhd6ZII/edit
